const KEY='mi-pequeno-campeon-v1';
const initial={profile:{babyName:'',motherName:'',partnerName:'',clinic:'',dueDate:'',lmpDate:'',doctor:'',bloodType:''},appointments:[],measurements:[],memories:[]};
let state=load();
function load(){try{return {...structuredClone(initial),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Intl.DateTimeFormat('es-PE',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00')):'—';
const short=d=>d?new Intl.DateTimeFormat('es-PE',{day:'2-digit',month:'short'}).format(new Date(d+'T12:00:00')):'—';
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
function gestation(date=new Date()){let due=state.profile.dueDate?new Date(state.profile.dueDate+'T12:00:00'):null;if(!due&&state.profile.lmpDate){due=new Date(state.profile.lmpDate+'T12:00:00');due.setDate(due.getDate()+280)}if(!due)return null;const daysLeft=Math.ceil((due-date)/86400000);const elapsed=280-daysLeft;return{week:Math.max(0,Math.min(42,Math.floor(elapsed/7))),daysLeft,due,progress:Math.max(0,Math.min(100,elapsed/280*100))}}
function getWeek(date){const g=gestation(new Date(date+'T12:00:00'));return g?.week||''}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function empty(){return $('#emptyTemplate').content.cloneNode(true)}
function render(){renderHero();renderStats();renderAppointments();renderMeasurements();renderMemories();renderProfile()}
function renderHero(){const g=gestation();$('#babyNameHero').textContent=state.profile.babyName||'Nuestro bebé';$('#weekNumber').textContent=g?.week??'—';$('#pregnancyProgress').style.width=(g?.progress||0)+'%';$('.week-ring').style.setProperty('--progress',(g?.progress||0)+'%');if(g){$('#weekMessage').textContent=`Estamos viviendo la semana ${g.week} de esta gran aventura.`;$('#daysMessage').textContent=g.daysLeft>=0?`Faltan aproximadamente ${g.daysLeft} días para conocernos.`:'La fecha probable ya llegó. ¡Falta muy poquito!'}else{$('#weekMessage').textContent='Completa la fecha probable de parto para calcular la semana.';$('#daysMessage').textContent='Todo comienza con un pequeño dato.'}}
function renderStats(){const future=state.appointments.filter(a=>new Date(a.date+'T'+(a.time||'23:59'))>=new Date()).sort((a,b)=>a.date.localeCompare(b.date))[0];$('#nextAppointment').textContent=future?short(future.date):'Sin registrar';$('#nextAppointmentDetail').textContent=future?`${future.type}${future.time?' · '+future.time:''}`:'Agrega tu siguiente control';const ms=[...state.measurements].sort((a,b)=>a.date.localeCompare(b.date));const last=ms.at(-1),first=ms[0];$('#lastWeight').textContent=last?.motherWeight?`${last.motherWeight} kg`:'— kg';$('#weightChange').textContent=last?.motherWeight&&first?.motherWeight&&last!==first?`${(last.motherWeight-first.motherWeight).toFixed(1)} kg desde el primer registro`:'Aún no hay cambio calculado';$('#lastHeartRate').textContent=last?.heartRate?`${last.heartRate} lpm`:'— lpm';$('#heartRateDate').textContent=last?.heartRate?fmt(last.date):'Último control';$('#memoryCount').textContent=state.memories.length}
function renderAppointments(){const el=$('#appointmentsList');el.innerHTML='';const items=[...state.appointments].sort((a,b)=>a.date.localeCompare(b.date));if(!items.length){el.append(empty());return}items.forEach(a=>{const d=new Date(a.date+'T12:00:00');const article=document.createElement('article');article.className='timeline-item';article.innerHTML=`<div class="date-box"><strong>${d.getDate()}</strong><span>${d.toLocaleDateString('es-PE',{month:'short'})}</span></div><div><h3>${esc(a.type)}</h3><p>${esc([a.time,a.place,a.professional].filter(Boolean).join(' · ')||'Sin detalles adicionales')}</p>${a.notes?`<p>${esc(a.notes)}</p>`:''}</div><button class="delete-btn no-print" data-delete="appointment" data-id="${a.id}" aria-label="Eliminar cita">Eliminar</button>`;el.append(article)})}
function renderMeasurements(){const list=$('#measurementsList'),chart=$('#weightChart');list.innerHTML='';chart.innerHTML='';const items=[...state.measurements].sort((a,b)=>a.date.localeCompare(b.date));const weighted=items.filter(x=>x.motherWeight).slice(-8);if(!weighted.length){chart.innerHTML='<div class="chart-empty">Tus mediciones aparecerán aquí</div>';$('#chartDelta').textContent='Sin datos'}else{const vals=weighted.map(x=>+x.motherWeight),min=Math.min(...vals)-1,max=Math.max(...vals)+1;weighted.forEach(x=>{const h=25+(+x.motherWeight-min)/(max-min||1)*145;chart.insertAdjacentHTML('beforeend',`<div class="bar-wrap"><b>${esc(x.motherWeight)}</b><div class="bar" style="height:${h}px"></div><small>${short(x.date)}</small></div>`)});$('#chartDelta').textContent=`${(vals.at(-1)-vals[0]).toFixed(1)} kg en el periodo`}if(!items.length){list.append(empty());return}items.slice().reverse().forEach(m=>{const metrics=[['Peso mamá',m.motherWeight&&m.motherWeight+' kg'],['Presión',m.bloodPressure],['Altura uterina',m.fundalHeight&&m.fundalHeight+' cm'],['Latidos',m.heartRate&&m.heartRate+' lpm'],['Peso bebé',m.babyWeight&&m.babyWeight+' g'],['Longitud',m.babyLength&&m.babyLength+' cm']].filter(x=>x[1]);const card=document.createElement('article');card.className='record-card';card.innerHTML=`<header><div><h3>Semana ${esc(m.week||getWeek(m.date)||'—')}</h3><small>${fmt(m.date)}</small></div><button class="delete-btn no-print" data-delete="measurement" data-id="${m.id}">Eliminar</button></header><div class="metrics">${metrics.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join('')}</div>${m.notes?`<p>${esc(m.notes)}</p>`:''}`;list.append(card)})}
function renderMemories(){const el=$('#memoriesGrid');el.innerHTML='';const items=[...state.memories].sort((a,b)=>a.date.localeCompare(b.date));if(!items.length){el.append(empty());return}items.forEach(m=>{const card=document.createElement('article');card.className='memory-card';card.innerHTML=`<div class="memory-photo">${m.photo?`<img src="${m.photo}" alt="${esc(m.title)}" />`:'Nuestro recuerdo'}</div><div class="memory-body"><div class="memory-meta"><span>${fmt(m.date)}${m.week?' · Semana '+esc(m.week):''}</span><button class="delete-btn no-print" data-delete="memory" data-id="${m.id}">Eliminar</button></div><h3>${esc(m.title)}</h3><p>${esc(m.text||'Un momento que guardaremos para siempre.')}</p></div>`;el.append(card)})}
function renderProfile(){const p=state.profile;const fields=[['Nuestro bebé',p.babyName||'Por completar'],['Mamá',p.motherName||'Por completar'],['Papá / acompañante',p.partnerName||'Por completar'],['Fecha probable',fmt(p.dueDate)],['Centro de salud',p.clinic||'Por completar'],['Profesional',p.doctor||'Por completar'],['Tipo de sangre',p.bloodType||'Por completar'],['Última regla',fmt(p.lmpDate)]];$('#profileSummary').innerHTML=fields.map(([a,b])=>`<div class="profile-field"><small>${a}</small><strong>${esc(b)}</strong></div>`).join('')}
function openDialog(type){const d=$('#'+type+'Dialog');const f=$('#'+type+'Form');if(f){f.reset();const date=f.elements.date;if(date)date.value=new Date().toISOString().slice(0,10);if(type==='measurement'&&f.elements.week)f.elements.week.value=gestation()?.week||''}d.showModal()}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openDialog(b.dataset.open)));
$('#editProfileBtn').addEventListener('click',()=>{const f=$('#profileForm');Object.entries(state.profile).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});$('#profileDialog').showModal()});
$('#saveProfile').addEventListener('click',e=>{e.preventDefault();state.profile=formData($('#profileForm'));save();$('#profileDialog').close()});
$('#appointmentForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const d=formData(e.currentTarget);state.appointments.push({...d,id:uid()});save()});
$('#measurementForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const d=formData(e.currentTarget);state.measurements.push({...d,id:uid()});save()});
$('#memoryForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const d=formData(e.currentTarget),file=e.currentTarget.elements.photo.files[0];if(file){if(file.size>5e6){alert('Elige una imagen menor de 5 MB para que el respaldo siga siendo liviano.');return}d.photo=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}else delete d.photo;state.memories.push({...d,id:uid()});save();$('#memoryDialog').close()});
document.addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(b&&confirm('¿Eliminar este registro?')){const map={appointment:'appointments',measurement:'measurements',memory:'memories'};state[map[b.dataset.delete]]=state[map[b.dataset.delete]].filter(x=>x.id!==b.dataset.id);save()}if(e.target.dataset.close)$('#'+e.target.dataset.close).close()});
$('#printBtn').addEventListener('click',()=>window.print());$('#backupBtn').addEventListener('click',()=>$('#backupDialog').showModal());
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mi-pequeno-campeon-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)});
$('#importInput').addEventListener('change',async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.profile||!Array.isArray(data.appointments)||!Array.isArray(data.measurements)||!Array.isArray(data.memories))throw Error();if(confirm('Esto reemplazará los datos actuales. ¿Continuar?')){state=data;save();$('#backupDialog').close()}}catch{alert('El archivo no es un respaldo válido de esta aplicación.')}});
if(!state.profile.dueDate&&!state.profile.babyName)setTimeout(()=>$('#profileDialog').showModal(),500);
render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
