const KEY='mi-pequeno-campeon-v1',DB_NAME='mi-pequeno-campeon',STORE='album';
const initial={profile:{babyName:'',babyGender:'boy',motherName:'',partnerName:'',clinic:'',dueDate:'',lmpDate:'',doctor:'',bloodType:''},appointments:[],measurements:[],memories:[]};
let state=structuredClone(initial),editing={type:null,id:null},activeTab='inicio',toastTimer;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const fmt=d=>d?new Intl.DateTimeFormat('es-PE',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00')):'—';
const short=d=>d?new Intl.DateTimeFormat('es-PE',{day:'2-digit',month:'short'}).format(new Date(d+'T12:00:00')):'—';
const normalize=data=>({profile:{...initial.profile,...(data?.profile||{})},appointments:Array.isArray(data?.appointments)?data.appointments:[],measurements:Array.isArray(data?.measurements)?data.measurements:[],memories:Array.isArray(data?.memories)?data.memories:[]});
function openDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(Error('IndexedDB no disponible'));const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function loadState(){try{const db=await openDb(),data=await new Promise((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).get(KEY);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});if(data)return normalize(data)}catch{}try{const old=JSON.parse(localStorage.getItem(KEY)||'null');if(old){const migrated=normalize(old);await persist(migrated);return migrated}}catch{}return structuredClone(initial)}
async function persist(value=state){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch(err){try{localStorage.setItem(KEY,JSON.stringify(value))}catch{throw Error('No hay espacio disponible para guardar')}}}
async function save(message='Cambios guardados'){try{await persist();render();showToast(message);navigator.vibrate?.(18)}catch(err){showToast(err.message||'No se pudo guardar')}}
function showToast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function gestation(date=new Date()){let due=state.profile.dueDate?new Date(state.profile.dueDate+'T12:00:00'):null;if(!due&&state.profile.lmpDate){due=new Date(state.profile.lmpDate+'T12:00:00');due.setDate(due.getDate()+280)}if(!due)return null;const daysLeft=Math.ceil((due-date)/86400000),elapsed=280-daysLeft;return{week:Math.max(0,Math.min(42,Math.floor(elapsed/7))),daysLeft,due,progress:Math.max(0,Math.min(100,elapsed/280*100))}}
const getWeek=date=>gestation(new Date(date+'T12:00:00'))?.week||'';
const formData=form=>Object.fromEntries(new FormData(form).entries());
const empty=()=>$('#emptyTemplate').content.cloneNode(true);
function render(){renderTheme();renderHero();renderStats();renderAppointments();renderMeasurements();renderMemories();renderProfile();setActiveTab(activeTab)}
function renderTheme(){const girl=state.profile.babyGender==='girl',brand=girl?'Mi Pequeña Campeona':'Mi Pequeño Campeón';document.body.dataset.theme=girl?'girl':'boy';document.querySelector('meta[name="theme-color"]').content=girl?'#59384d':'#173a53';$('#appBrandName').textContent=brand;$('#footerBrand').textContent=brand;document.title=brand;$('.hero-intro').textContent=girl?'Citas, medidas, ecografías y pequeños recuerdos de la espera de nuestra mujercita.':'Citas, medidas, ecografías y pequeños recuerdos de la espera de nuestro hombrecito.';$('.quote-card span').textContent=girl?'Para nuestra pequeña campeona':'Para nuestro pequeño campeón'}
function renderHero(){const g=gestation();$('#babyNameHero').textContent=state.profile.babyName||'Nuestro bebé';$('#weekNumber').textContent=g?.week??'—';$('#pregnancyProgress').style.width=(g?.progress||0)+'%';$('.week-ring').style.setProperty('--progress',(g?.progress||0)+'%');if(g){$('#weekMessage').textContent=`Estamos viviendo la semana ${g.week} de esta gran aventura.`;$('#daysMessage').textContent=g.daysLeft>=0?`Faltan aproximadamente ${g.daysLeft} días para conocernos.`:'La fecha probable ya llegó. ¡Falta muy poquito!'}else{$('#weekMessage').textContent='Completa la fecha probable de parto para calcular la semana.';$('#daysMessage').textContent='Todo comienza con un pequeño dato.'}}
function renderStats(){const future=state.appointments.filter(a=>new Date(a.date+'T'+(a.time||'23:59'))>=new Date()).sort((a,b)=>a.date.localeCompare(b.date))[0];$('#nextAppointment').textContent=future?short(future.date):'Sin registrar';$('#nextAppointmentDetail').textContent=future?`${future.type}${future.time?' · '+future.time:''}`:'Agrega tu siguiente control';const ms=[...state.measurements].sort((a,b)=>a.date.localeCompare(b.date)),last=ms.at(-1),first=ms[0];$('#lastWeight').textContent=last?.motherWeight?`${last.motherWeight} kg`:'— kg';$('#weightChange').textContent=last?.motherWeight&&first?.motherWeight&&last!==first?`${(+last.motherWeight-+first.motherWeight).toFixed(1)} kg desde el primer registro`:'Aún no hay cambio calculado';$('#lastHeartRate').textContent=last?.heartRate?`${last.heartRate} lpm`:'— lpm';$('#heartRateDate').textContent=last?.heartRate?fmt(last.date):'Último control';$('#memoryCount').textContent=state.memories.length}
function renderAppointments(){const el=$('#appointmentsList');el.innerHTML='';const items=[...state.appointments].sort((a,b)=>a.date.localeCompare(b.date));if(!items.length){el.append(empty());return}items.forEach(a=>{const d=new Date(a.date+'T12:00:00'),article=document.createElement('article');article.className='timeline-item';article.innerHTML=`<div class="date-box"><strong>${d.getDate()}</strong><span>${d.toLocaleDateString('es-PE',{month:'short'})}</span></div><div><h3>${esc(a.type)}</h3><p>${esc([a.time,a.place,a.professional].filter(Boolean).join(' · ')||'Sin detalles adicionales')}</p>${a.notes?`<p>${esc(a.notes)}</p>`:''}</div><div class="record-actions no-print"><button class="edit-btn" data-edit="appointment" data-id="${a.id}">Editar</button><button class="delete-btn" data-delete="appointment" data-id="${a.id}">Eliminar</button></div>`;el.append(article)})}
function renderMeasurements(){const list=$('#measurementsList'),chart=$('#weightChart');list.innerHTML='';chart.innerHTML='';const items=[...state.measurements].sort((a,b)=>a.date.localeCompare(b.date)),weighted=items.filter(x=>x.motherWeight).slice(-8);if(!weighted.length){chart.innerHTML='<div class="chart-empty">Tus mediciones aparecerán aquí</div>';$('#chartDelta').textContent='Sin datos'}else{const vals=weighted.map(x=>+x.motherWeight),min=Math.min(...vals)-1,max=Math.max(...vals)+1;weighted.forEach(x=>{const h=25+(+x.motherWeight-min)/(max-min||1)*145;chart.insertAdjacentHTML('beforeend',`<div class="bar-wrap"><b>${esc(x.motherWeight)}</b><div class="bar" style="height:${h}px"></div><small>${short(x.date)}</small></div>`)});$('#chartDelta').textContent=`${(vals.at(-1)-vals[0]).toFixed(1)} kg en el periodo`}if(!items.length){list.append(empty());return}items.slice().reverse().forEach(m=>{const metrics=[['Peso mamá',m.motherWeight&&m.motherWeight+' kg'],['Presión',m.bloodPressure],['Altura uterina',m.fundalHeight&&m.fundalHeight+' cm'],['Latidos',m.heartRate&&m.heartRate+' lpm'],['Peso bebé',m.babyWeight&&m.babyWeight+' g'],['Longitud',m.babyLength&&m.babyLength+' cm']].filter(x=>x[1]),card=document.createElement('article');card.className='record-card';card.innerHTML=`<header><div><h3>Semana ${esc(m.week||getWeek(m.date)||'—')}</h3><small>${fmt(m.date)}</small></div><div class="record-actions no-print"><button class="edit-btn" data-edit="measurement" data-id="${m.id}">Editar</button><button class="delete-btn" data-delete="measurement" data-id="${m.id}">Eliminar</button></div></header><div class="metrics">${metrics.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join('')}</div>${m.notes?`<p>${esc(m.notes)}</p>`:''}`;list.append(card)})}
function renderMemories(){const el=$('#memoriesGrid');el.innerHTML='';const items=[...state.memories].sort((a,b)=>a.date.localeCompare(b.date));if(!items.length){el.append(empty());return}items.forEach((m,index)=>{const card=document.createElement('article');card.className='memory-card';card.innerHTML=`<div class="memory-photo">${m.photo?`<img src="${m.photo}" alt="${esc(m.title)}" />`:`<span>${index===0?'Nuestro primer capítulo':'Un recuerdo nuestro'}</span>`}</div><div class="memory-body"><div class="memory-meta"><span>${fmt(m.date)}${m.week?' · Semana '+esc(m.week):''}</span><div class="record-actions no-print"><button class="edit-btn" data-edit="memory" data-id="${m.id}">Editar</button><button class="delete-btn" data-delete="memory" data-id="${m.id}">Eliminar</button></div></div><h3>${esc(m.title)}</h3><p>${esc(m.text||'Un momento que guardaremos para siempre.')}</p></div>`;el.append(card)})}
function renderProfile(){const p=state.profile,girl=p.babyGender==='girl',fields=[['Nuestro bebé',p.babyName||'Por completar'],[girl?'Esperamos una':'Esperamos un',girl?'Mujercita':'Hombrecito'],['Mamá',p.motherName||'Por completar'],['Papá / acompañante',p.partnerName||'Por completar'],['Fecha probable',fmt(p.dueDate)],['Centro de salud',p.clinic||'Por completar'],['Profesional',p.doctor||'Por completar'],['Tipo de sangre',p.bloodType||'Por completar']];$('#profileSummary').innerHTML=fields.map(([a,b])=>`<div class="profile-field"><small>${a}</small><strong>${esc(b)}</strong></div>`).join('')}
function fillForm(form,data){Object.entries(data||{}).forEach(([k,v])=>{const field=form.elements[k];if(!field||k==='photo')return;if(field instanceof RadioNodeList){const radio=[...field].find(x=>x.value===v);if(radio)radio.checked=true}else field.value=v??''})}
function openDialog(type,id=null){editing={type,id};const dialog=$('#'+type+'Dialog'),form=$('#'+type+'Form');if(form)form.reset();const data=id?(type==='appointment'?state.appointments:type==='measurement'?state.measurements:state.memories).find(x=>x.id===id):null;if(data)fillForm(form,data);if(type==='appointment')$('#appointmentModalTitle').textContent=id?'Editar cita':'Nueva cita';if(type==='measurement')$('#measurementModalTitle').textContent=id?'Editar control':'Registrar evolución';if(type==='memory'){ $('#memoryModalTitle').textContent=id?'Editar recuerdo':'Guardar un momento';$('#removePhotoRow').classList.toggle('visible',Boolean(data?.photo)) }if(!id&&form){const date=form.elements.date;if(date)date.value=new Date().toISOString().slice(0,10);if(type==='measurement'&&form.elements.week)form.elements.week.value=gestation()?.week||''}dialog.showModal()}
function upsert(collection,data){const i=collection.findIndex(x=>x.id===editing.id);if(i>=0)collection[i]={...collection[i],...data,id:editing.id};else collection.push({...data,id:uid()})}
async function compressImage(file){if(!file)return null;const bitmap=await createImageBitmap(file),max=1600,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return canvas.toDataURL('image/jpeg',.82)}
function setActiveTab(tab,shouldScroll=false){activeTab=tab;$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.app-screen').forEach(s=>s.classList.toggle('active-screen',s.dataset.screen===tab));if(shouldScroll)window.scrollTo({top:0,behavior:'instant'});$('#fabBtn').style.display=tab==='perfil'?'none':''}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openDialog(b.dataset.open)));
$('#editProfileBtn').addEventListener('click',()=>{const f=$('#profileForm');f.reset();fillForm(f,state.profile);$('#profileDialog').showModal()});
$('#saveProfile').addEventListener('click',async e=>{e.preventDefault();state.profile={...state.profile,...formData($('#profileForm'))};await save('Perfil actualizado');$('#profileDialog').close()});
$('#appointmentForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();upsert(state.appointments,formData(e.currentTarget));await save(editing.id?'Cita actualizada':'Cita guardada');$('#appointmentDialog').close()});
$('#measurementForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();upsert(state.measurements,formData(e.currentTarget));await save(editing.id?'Control actualizado':'Control guardado');$('#measurementDialog').close()});
$('#memoryForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const data=formData(e.currentTarget),file=e.currentTarget.elements.photo.files[0],old=editing.id?state.memories.find(x=>x.id===editing.id):null;delete data.removePhoto;try{if(file)data.photo=await compressImage(file);else if(old?.photo&&!e.currentTarget.elements.removePhoto.checked)data.photo=old.photo;else delete data.photo;upsert(state.memories,data);await save(editing.id?'Recuerdo actualizado':'Recuerdo guardado');$('#memoryDialog').close()}catch{showToast('No pudimos procesar esa imagen')}});
document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openDialog(edit.dataset.edit,edit.dataset.id);if(del&&confirm('¿Eliminar este registro?')){const map={appointment:'appointments',measurement:'measurements',memory:'memories'};state[map[del.dataset.delete]]=state[map[del.dataset.delete]].filter(x=>x.id!==del.dataset.id);await save('Registro eliminado')}if(e.target.dataset.close)$('#'+e.target.dataset.close).close()});
$$('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>setActiveTab(b.dataset.tab,true)));
$('#fabBtn').addEventListener('click',()=>{const map={inicio:'appointment',citas:'appointment',evolucion:'measurement',recuerdos:'memory'};if(map[activeTab])openDialog(map[activeTab])});
$('#printBtn').addEventListener('click',()=>window.print());$('#backupBtn').addEventListener('click',()=>$('#backupDialog').showModal());
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mi-album-prenatal-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});
$('#importInput').addEventListener('change',async e=>{try{const data=normalize(JSON.parse(await e.target.files[0].text()));if(confirm('Esto reemplazará los datos actuales. ¿Continuar?')){state=data;await save('Respaldo restaurado');$('#backupDialog').close()}}catch{showToast('El archivo no es un respaldo válido')}});
async function init(){state=await loadState();render();if(!state.profile.dueDate&&!state.profile.babyName)setTimeout(()=>{$('#profileForm').reset();fillForm($('#profileForm'),state.profile);$('#profileDialog').showModal()},500);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
init();
